version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "serverless-blog-platform"
s3_bucket = "sam-deploy-bucket-unique-id"
s3_prefix = "serverless-blog-platform"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=Prod"
